### ISSUE TITLE
Looking for CL code?

### ISSUE THREAD

**Issue by PatrickAlphaC** [coderrick/ethonline2020-dewdlabs#1]
Hi Coderrick!

I LOVE seeing how you keep improving at each hackathon! Bravo!

I'm looking for the chainlink section in your code, but I can't seem to find it? Could you direct me?

**Comment by Wilson-Duncan** [comment]
Thanks, no problem. The latest commit should have everything in a
reasonable order. I also attached screenshots.

Derrick Wilson - Duncan
Temple University, B.S. Computer Science
derrick.duncan@temple.edu
www.linkedin.com/in/derrick-wilson-duncan-5ab07053
https://github.com/coderrick
<https://github.com/coderrick>

**Comment by PatrickAlphaC** [comment]
Got it, thank you!
